[tool.black]
target-version = ['py39']

[tool.isort]
profile = "black"

[tool.ruff]
output-format = "github"
target-version = "py39"

[tool.ruff.lint]
ignore = [
  "D10",  # TODO: we are missing many docstrings
  "D203",  # CONFIG: incompatible with D211
  "D212",  # CONFIG: incompatible with D213
  "T201",  # WONTFIX: using print() (maybe add noqa)
  "PLW2901"  # TODO: overwriting variables inside loop
]
select = [
  "E",
  "F",
  "B",
  "I",
  "T10",
  "A",
  "C4",
  "C90",
  "YTT",
  "DJ",
  "UP",
  "D",
  "PD",
  "PGH",
  "PL",
  "TRY",
  "RUF",
  "ERA",
  "ICN",
  "ISC",
  "EXE",
  "INP",
  "PIE",
  "G",
  "PYI",
  "Q",
  "SIM",
  "TID",
  "RSE",
  "T20",
  "RET",
  "SLF",
  "N"
]

[tool.ruff.lint.mccabe]
max-complexity = 16
