# Copyright © Michal Čihař <michal@weblate.org>
#
# SPDX-License-Identifier: MIT

name: Tests

on:
  push:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        python-version:
        - '3.9'
        - '3.10'
        - '3.11'
        - '3.12'
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - uses: actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97 # v7.0.0
      with:
        python-version: ${{ matrix.python-version }}
    - run: sudo apt update
    - run: sudo apt install munin-node
    - name: munin-node-configure
      run: |
        BLANKDIR=$(mktemp -d)
        /usr/sbin/munin-node-configure --servicedir "$BLANKDIR" --sconfdir "$BLANKDIR" --libdir . --suggest --debug || true
        /usr/sbin/munin-node-configure --servicedir "$BLANKDIR" --sconfdir "$BLANKDIR" --libdir . --suggest > test/out || true
        diff -u test/expected test/out
permissions:
  contents: read
